name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Step 2: Set up JDK (Optional, if not already available)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
    
    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    
    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t demotask:${GITHUB_SHA} .
